pub mod color;
pub mod copy_struct;
pub mod learn_init_struct;
pub mod learn_init_struct_2;
pub mod learn_init_struct_3;
pub mod learn_init_tuple_struct;
pub mod print_user;
pub mod struct_method;
pub mod user;
